### ISSUE TITLE
Service Worker for homescreen goodness!

### ISSUE THREAD

**Issue by cdroulers** [cdroulers/block-fly#12]
Use a service worker to get everything set up, be happy with life.

**Comment by olafleur** [comment]
What would be a concrete improvement that a service worker would bring ?

**Comment by cdroulers** [comment]
Mostly having fun with doing it! But it's a good enhancement for browsers that support it, since it'll ask the user if they want to add the site to their homescreen as an app and it can function fully offline and reduce traffic.

Other than that, there's no real reason, I just wanna mess around with it, especially with webpack since there seems to be plugins for it!

**Comment by cdroulers** [comment]
https://github.com/NekR/offline-plugin

https://github.com/oliviertassinari/serviceworker-webpack-plugin

Offline plugin is way more automatic, but the other plugin gives more control!
First one also falls back to AppCache if serviceWorker isn't implemented!

**Comment by cdroulers** [comment]
offline plugin it is! Also needs HTTPS on production server!

**Comment by cdroulers** [comment]
Gotta test other browsers for serviceWorker and AppCache!

**Comment by cdroulers** [comment]
HTTPS: https://cdroulers.com/blog/2017/02/08/https-everywhere/
