### ISSUE TITLE
Show current level as a floating icon at the top.

### ISSUE THREAD

**Issue by cdroulers** [cdroulers/block-fly#14]
To know where we are.

**Comment by olafleur** [comment]
Do you mean a floating icon inside our outside the canvas ?

**Comment by cdroulers** [comment]
Inside, just a small thing!

**Comment by olafleur** [comment]
ok :)

**Comment by cdroulers** [comment]
I'll probably refactor level sets (JSON files and code) to have more metadata for levels. Like a password for going back to previously passed levels, a title, an index, etc. If you're working on this, make sure the icon can have a number and a short text after!

**Comment by olafleur** [comment]
I'm not working on that for the moment. Will get back to you when I'll have more time. ;)

**Comment by olafleur** [comment]
Closing as this is done. Good job @cdroulers !
