### ISSUE TITLE
Replace the default JavaScript alert by something more beautiful.

### ISSUE THREAD

**Issue by olafleur** [cdroulers/block-fly#19]

**Comment by cdroulers** [comment]
Orjust remove the alert. It's not that uaeful anymore with the level display.

**Comment by olafleur** [comment]
So, nous feedback at all? I quitte enjoy having positive feedback when solving à tricky puzzle. ;)

**Comment by cdroulers** [comment]
I was thinking of implementing material design using MDL (Material Design Lite https://getmdl.io/), so maybe using the snackbar would be good, since it's non-intrusive.

**Comment by olafleur** [comment]
Ok, I will give it a try. ;)
