### ISSUE TITLE
UI tests with testcafe maybe

### ISSUE THREAD

**Issue by cdroulers** [cdroulers/block-fly#31]
To test ui buttons and whatnot. Tests are only on game logic so far.

**Comment by miherlosev** [comment]
Hi, 
I can setup [TestCafe](https://github.com/DevExpress/testcafe) and write a first set of tests

**Comment by cdroulers** [comment]
Sounds good! Are you guys searching for testcafe and offering help for marketing?

I think a simple test that verifies loading of page and that buttons work would be good!

**Comment by miherlosev** [comment]
> Are you guys searching for testcafe and offering help for marketing?

Yeah, kind of.

> I think a simple test that verifies loading of page and that buttons work would be good!

Ok. It is very simple - I can do this very fast

**Comment by cdroulers** [comment]
Will it work in typescript?

**Comment by miherlosev** [comment]
At present, you can write tests using ES2016.
We have plans to implement native support of TypeScript.
You can vote for a corresponding issue 
https://github.com/DevExpress/testcafe/issues/408
and track progress of this.

**Comment by cdroulers** [comment]
Sounds good. Thanks!

**Comment by miherlosev** [comment]
I found a bug in testcafe related to drawing on the 'canvas' element.
https://github.com/DevExpress/testcafe-hammerhead/issues/1033

I can create a pull request with the first test set, because this bug doesn't block test writing.
Or I can do this after this bug is fixed.
What do you prefer?

**Comment by cdroulers** [comment]
PR whatvever you have!

**Comment by miherlosev** [comment]
Done - https://github.com/cdroulers/block-fly/pull/33
