### ISSUE TITLE
Resizable viewport for better mobile experience.

### ISSUE THREAD

**Issue by cdroulers** [cdroulers/block-fly#4]
resize properly for everything is visible. Allow paning with swipes and udal-touch or whatever.

**Comment by cdroulers** [comment]
Probably remove swipe to move and use it for panning? Or use dual-touch for panning.

**Comment by cdroulers** [comment]
@olafleur Any comments on the code so far? Will allow panning with "shift + arrows" on next commit and look into panning for mobile.

**Comment by olafleur** [comment]
LGTM for the moment. Love the fact that we can always see the fly on desktop, even with resized window. :)

**Comment by cdroulers** [comment]
Was finished, but not closed!
